module.exports = {
  network: {
    failure: '通信に失敗しました。しばらく時間をあけてから、やり直してください。',
    error: '通信エラーが発生しました。しばらく時間をあけてから、やり直してください。'
  },
  system: {
    error: 'エラーが発生しました。しばらく時間をあけてから、やり直してください。'
  },
  auth: {
    signed_out: 'ログアウトしました。',
    already_authenticated: '既にログインしています。',
    already_signed_out: '既にログアウトされています。',
    unauthenticated: 'ログインしてください。'
  }
}
